#!/bin/sh

if [ ! -d Bin ]; then mkdir Bin; fi

if [ -e $probdir/build.sh ]; then
  . $probdir/build.sh
else
  case $lang in
    cpp)
      g++ -o Bin/main-program Src/Main.cpp || exit 1 ;;
    java)
      javac -d Bin Src/Main.java || exit 1 ;;
    *) echo "No such language" >&2 ; exit 1 ;;
  esac
fi
