#!/bin/sh

export prob=$2
export lang=$3
export langdir=$(cd $(dirname $0)/lang/$lang && pwd)
export probdir=$(cd $(dirname $0)/../prob/$prob && pwd)
export PATH=$(cd $(dirname $0) && pwd):$PATH
cd $1
shift; shift; shift
$@
